# Generated by Django 3.0.5 on 2021-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
