# Generated by Django 3.0.5 on 2021-01-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_track_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='location',
            new_name='locations',
        ),
    ]
